version: 1

formatters:
  custmoFormatter:
    format: '%(asctime)s %(levelname)s - %(funcName)s: %(message)s'

loggers:
  file:
    handlers: [fileRotatingHandler]
    level: INFO
    qualname: file
    propagate: no

  console:
    handlers: [consoleHandler]
    level: DEBUG
    qualname: console
    propagate: no

handlers:
  fileRotatingHandler:
    formatter: custmoFormatter
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    filename: logs/server.log
    encoding: utf8
    when: 'D'
    interval: 1
    backupCount: 14

  errorFileRotatingHandler:
    formatter: custmoFormatter
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    filename: logs/server_error.log
    encoding: utf8
    maxBytes: 10000000
    backupCount: 100

  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: custmoFormatter
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [fileRotatingHandler,errorFileRotatingHandler,consoleHandler]